const tankStats = {
    "Tank": {
        upgradesFrom: "None",
        level: 1,
        turrets: 1,
        bullets: 3,
        bulletDamage: 115,
        bulletPenatration: 115,
        bulletSpeed: 15,
        reload: 1,
        healthRegen: 5,
        maxHealth: 50,
        bodyDamage: 5,
        movementSpeed: 5,
    },


    "Single": {
        upgradesFrom: "Tank",
        level: 45,
        turrets: 1,
        bullets: 1,
        bulletDamage: 77,
        bulletPenatration: 77,
        bulletSpeed: 37,
        reload: 0.5,
        healthRegen: 10,
        maxHealth: 60,
        bodyDamage: 10,
        movementSpeed: 7,
    },

    // "Mayhem": {
    //     upgradesFrom: "Single",
    //     level: 60,
    //     turrets: 1,
    //     bullets: 50,
    //     bulletDamage: 77,
    //     bulletPenatration: 77,
    //     bulletSpeed: 37,
    //     reload: 10,
    //     healthRegen: 10,
    //     maxHealth: 120,
    //     bodyDamage: 10,
    //     movementSpeed: 7,
    // },

    // "Ratatatata": {
    //     upgradesFrom: "Mayhem",
    //     level: 75,
    //     turrets: 1,
    //     bullets: 7,
    //     bulletDamage: 777,
    //     bulletPenatration: 777,
    //     bulletSpeed: 77,
    //     reload: 1,
    //     healthRegen: 77,
    //     maxHealth: 777,
    //     bodyDamage: 77,
    //     movementSpeed: 7,
    // },

    "Twin": {
        upgradesFrom: "Tank",
        level: 15,
        turrets: 2,
        bullets: 1,
        bulletDamage: 2,
        bulletPenatration: 2,
        bulletSpeed: 19,
        reload: 6,
        healthRegen: 9,
        maxHealth: 54,
        bodyDamage: 9,
        movementSpeed: 9,
    },

    "Sniper": {
        upgradesFrom: "Tank",
        level: 15,
        turrets: 1,
        bullets: 1,
        bulletDamage: 9,
        bulletPenatration: 9,
        bulletSpeed: 20,
        reload: 9.5,
        healthRegen: 9,
        maxHealth: 54,
        bodyDamage: 9,
        movementSpeed: 9,
    },

    "Machine-Gun": {
        upgradesFrom: "Tank",
        level: 15,
        turrets: 1,
        bullets: 2,
        bulletDamage: 2,
        bulletPenatration: 9,
        bulletSpeed: 19,
        reload: 5.5,
        healthRegen: 9,
        maxHealth: 54,
        bodyDamage: 9,
        movementSpeed: 9,
        accuracy: 0.20000
    },

    "Flank-Guard": {
        upgradesFrom: "Tank",
        level: 15,
        turrets: 2,
        bullets: 1,
        bulletDamage: 9,
        bulletPenatration: 9,
        bulletSpeed: 19,
        reload: 6,
        healthRegen: 9,
        maxHealth: 54,
        bodyDamage: 9,
        movementSpeed: 9,
    },

    "Smasher": {
        upgradesFrom: "Tank",
        level: 30,
        turrets: 0,
        bullets: 0,
        bulletDamage: 0,
        bulletPenatration: 0,
        bulletSpeed: 0,
        reload: 0,
        healthRegen: 9,
        maxHealth: 54,
        bodyDamage: 10,
        movementSpeed: 9,
    },

    "Spike": {
        upgradesFrom: "Smasher",
        level: 45,
        turrets: 0,
        bullets: 0,
        bulletDamage: 0,
        bulletPenatration: 0,
        bulletSpeed: 0,
        reload: 0,
        healthRegen: 14,
        maxHealth: 60,
        bodyDamage: 18,
        movementSpeed: 10,
    },

    "Mega-Smasher": {
        upgradesFrom: "Smasher",
        level: 45,
        turrets: 0,
        bullets: 0,
        bulletDamage: 0,
        bulletPenatration: 0,
        bulletSpeed: 0,
        reload: 0,
        healthRegen: 10,
        maxHealth: 100,
        bodyDamage: 10,
        movementSpeed: 10,
    },

    "Ball": {
        upgradesFrom: "Tank",
        level: 777,
        turrets: 66,
        bullets: 1,
        bulletDamage: 777,
        bulletPenatration: 777,
        bulletSpeed: 37,
        reload: 10,
        healthRegen: 777,
        maxHealth: 777,
        bodyDamage: 777,
        movementSpeed: 17,
        accuracy: 8
    },
}

export default tankStats